### PR TITLE
Output all processors and use a list comprehension

### PR DESCRIPTION
**Pull request by nilp0inter**
WIP, not tested

### CODE REVIEW

**Review by panchoh — APPROVED** [review]

**Comment by panchoh** [comment]
@nilp0inter, `feature/dpkg` is a WIP branch in itself.  You are welcome to push your changes directly.

Thanks a bunch!

**Comment by nilp0inter** [comment]
What should happen with the package "python-dev"???

**Comment by panchoh** [comment]
It should be stripped of the standard suffix -dev, leaving a bare python.

-- 
pancho horrillo

**Comment by nilp0inter** [comment]
But `python` is also a prefix to be stripped. That means tha suffix stripping takes precedence over prefix stripping abd should be done iff there are more than one token?

**Pull request merged**
